### ISSUE TITLE
Bloated size?

### ISSUE THREAD

**Issue by Akkuma** [tiagorg/marionette-vdom#12]
Something seems very wrong with the size of this when you look at the size of marionette and the size of virtual-dom. There seems to be a lot of bloat being generated through browserify. I'm seeing Streams, Buffers, etc. in there and I would think none of this is needed, since mercury.js is almost 4x smaller when unminified files are compared.

**Comment by jrolfs** [comment]
Yeah, I was wondering the exact same thing. The main demo bundle is almost 3MB too o_O.

**Comment by tiagorg** [comment]
After spending a long time on this I concluded the bundle is big because of my dependencies' dependencies. The vdom library is quite heavy on dependencies.

Anyway, I have just released v0.2.1 with Marionette 3 support, updated dependencies, updated samples (demo, perf), updated documentation and reduced minified bundle by using uglifyjs dead code removal. 

I was able to get it down to 196KB minified non-gzipped. And it does not include Marionette, Backbone, Underscore or jQuery.

**Comment by tiagorg** [comment]
I will close it for now since I can't think of anything else to to. Just for the record I tired Google Closure Compiler (advanced compiling) that has some aggressive optimization and it broke, but the file size was not much less than what I got from uglifyjs (about 10KB less).
