### ISSUE TITLE
Is this module still recommended?

### ISSUE THREAD

**Issue by mykone** [tiagorg/marionette-vdom#13]
Hello @tiagorg, thanks for taking the initiative in writing these ports from Marionette.ItemView and Marionette.CompositeView. I notice there hasn't been any updates in the last 11 months. Is this still a recommended method to improve performance in Backbone/Marionette apps, or are people moving to more a Marionette-React solution?

Thanks in advance for your response.

**Comment by tiagorg** [comment]
Hi @mykone, thanks for asking! 

Indeed this project, although fully-functional for what it has accomplished, and passing in all unit tests from the current Marionette version when it was released, hasn't received much support from me in the past 11 months. 

The main idea behind this is optimize the generic rendering from Marionette Views (using templates from any templating library of the user's choice) using Virtual DOM rendering in a React-similar fashion.

Since Marionette.js is heavily based in views and behaviors I would think that putting React into the mix would not take advantage of the best features of Marionette, and that is basically why we have started this project back in the day. 

Anyhow I would love to know your take on this. If you are planning to give it a try I would love your feedback!

**Comment by mykone** [comment]
Thanks for your reply @tiagorg. I would give it a try, but if the Virtual Dom rendering won't increase performance that much, then I don't think it would be worth the time converting all my views to use the vdom. Also, another issue as someone else as pointed out is the size of the project. I really love Marionette and have been using it over 3 years now. I'm a die-hard fan, and would love if Marionette would get strong with their rendering, and if possible completely move away from Backbone.View.

**Comment by tiagorg** [comment]
I have just released v0.2.1 which now supports Marionette 3 and I was able to reduce the minified bundle size a bit by using uglifyjs dead code removal. Hence I am closing this issue for now. Thanks!
